'use client'

import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "../shared/styles/globals.css";
import StoreProvider from "./StoreProvider";
import { GlobalThemeContext, Themes } from "./context/GlobalThemeContext";
import { useContext, useState } from "react";
import ReactQueryProvider from "./ReactQueryProvider";

const inter = Nunito({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Cate Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [theme, setTheme] = useState<Themes>(Themes.DEFAULT)

  const defaultContext = {
    defaultContext: {
      [Themes.DARK]:  {
          appBackColor: '#23262f',
          interfaceBackColor: '#272c32',
          itemBackColor: '#2c333d',
          textColor: '#fff',
          iconsColor: '#fff',
          btnColor: '#fff',
          inputBorderColor: '#3d4756',
          btnBorderColor: '#3d4756',
          btnTextColor: '#fff',
      },
      [Themes.DEFAULT]: {
          appBackColor: '#181b1f',
          interfaceBackColor: '#21272f',
          itemBackColor: '#2c333d',
          textColor: '#fff',
          iconsColor: '',
          inputBorderColor: '#3d4756',
          btnColor: '#22979d',
          btnBorderColor: '#3d4756',
          btnTextColor: '#fff'
      }
  },
    currentTheme: theme,
    setTheme: setTheme
}
  
  const themes = useContext(GlobalThemeContext)
  const themeType = themes.defaultContext[themes.currentTheme]

  return (
    <StoreProvider>
      <GlobalThemeContext.Provider value={defaultContext}>
        <html lang="en">
          <body className={inter.className}>
            <ReactQueryProvider>
              <main style={{backgroundColor: themeType.appBackColor, position: 'relative', minHeight: '100vh'}}>
                {children}
              </main>
            </ReactQueryProvider>
          </body>
        </html>
      </GlobalThemeContext.Provider>
    </StoreProvider>
  );
}
